version: 2.1
jobs:
  build:
    working_directory: /go/src/github.com/Silmi3607/invoicer-chapter3
    docker:
      - image: circleci/golang:1.8
    environment:
      GO15VENDOREXPERIMENT: 1
    branches:
      only:
        - main
    steps:
      - checkout
      - setup_remote_docker

      - run: echo 'export GOPATH_HEAD="$(echo ${GOPATH}|cut -d ':' -f 1)"' >> $BASH_ENV
      - run: echo 'export GOPATH_BASE="${GOPATH_HEAD}/src/github.com/invoice"' >> $BASH_ENV
      - run: mkdir -p "${GOPATH_BASE}"
      - run: mkdir -p "${GOPATH_HEAD}/bin"
      - run: go get github.com/govend/govend

      - run:
          name: Build application
          command: |
            go install --ldflags '-extldflags "-static"' github.com/invoicer;
            mkdir -p bin;
            cp "${GOPATH_HEAD}/bin/invoicer" bin/invoicer;
            echo "Application built successfully."

      - run:
          name: Deploy application locally
          command: |
            DEPLOY_DIR="/mnt/c/Users/User/Desktop/invoicer-chapter3"
            mkdir -p ${DEPLOY_DIR}
            cp bin/invoicer ${DEPLOY_DIR}/invoicer
            echo "Application deployed to ${DEPLOY_DIR}"

      - run:
          name: Run application in background
          command: |
            ssh User@192.168.0.107 "${DEPLOY_DIR}/invoicer &"
          background: true

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
