version: 2.1

jobs:
  build:
    working_directory: /go/src/github.com/Silmi3607/invoicer
    docker:
      - image: circleci/golang:1.11
    environment:
      GO111MODULE: on
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build application
          command: |
            cd /go/src/github.com/Silmi3607/invoicer
            go build -o bin/invoicer .
            echo "Application built successfully."

      - run:
          name: Deploy application locally
          command: |
            DEPLOY_DIR="/mnt/c/Users/User/Desktop/invoicer-chapter3"
            mkdir -p ${DEPLOY_DIR}
            cp bin/invoicer ${DEPLOY_DIR}/invoicer
            echo "Application deployed to ${DEPLOY_DIR}"

      - run:
          name: Run application in background
          command: |
            ssh User@192.168.0.107 "${DEPLOY_DIR}/invoicer &"
          background: true

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
